/* Generated by re2c 0.16 on Sun May 15 12:49:29 2016 */
#include <string>
#include <cassert>
#include "lexer.h"
#include "parser.h"

#define YYCTYPE char

Lexer::Lexer(const std::string& str) :
	StrVal(str),
	PrevCursor(StrVal.data()),
	Cursor(StrVal.data()),
	CurrentToken(-1)
{

}
Lexer::Lexer(FILE* f) :
	CurrentToken(-1)
{
	fseek(f, 0, SEEK_END);
	long fsize = ftell(f);
	rewind(f);
	
	char* string = new char[fsize + 1];
	fread(string, fsize, 1, f);
	string[fsize] = '\0';

	StrVal = string;
	delete[] string;
	PrevCursor = StrVal.data();
	Cursor = StrVal.data();
}

size_t Lexer::TokenSize() const
{
	return (size_t)(Cursor - PrevCursor);
}
const char* Lexer::TokenText() const
{
	return PrevCursor;
}

int Lexer::NextToken()
{
	const YYCTYPE* YYMARKER;
	PrevCursor = Cursor;
	CurrentToken = -1;

start:
	{
#define YYMAXFILL 3

		
{
	YYCTYPE yych;
	yych = *Cursor;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy6;
	case '+':
	case '-':	goto yy8;
	case ',':	goto yy9;
	case '/':	goto yy11;
	case '0':	goto yy12;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy14;
	case ':':	goto yy16;
	case ';':	goto yy18;
	case '<':	goto yy20;
	case '>':	goto yy22;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy24;
	case '{':	goto yy27;
	case '}':	goto yy29;
	default:	goto yy4;
	}
yy2:
	++Cursor;
	{ CurrentToken = 0;                goto end; }
yy4:
	++Cursor;
yy5:
	{ CurrentToken = 0xFF;             goto end; }
yy6:
	++Cursor;
	{ PrevCursor = Cursor; goto start; }
yy8:
	yych = *++Cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy31;
	default:	goto yy5;
	}
yy9:
	++Cursor;
	{ CurrentToken = TOKEN_COMMA;      goto end; }
yy11:
	yych = *++Cursor;
	switch (yych) {
	case '/':	goto yy33;
	default:	goto yy5;
	}
yy12:
	yych = *(YYMARKER = ++Cursor);
	switch (yych) {
	case 'X':
	case 'x':	goto yy38;
	default:	goto yy15;
	}
yy13:
	{ CurrentToken = TOKEN_NUMBER;     goto end; }
yy14:
	YYMARKER = ++Cursor;
	yych = *Cursor;
yy15:
	switch (yych) {
	case '.':	goto yy36;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy14;
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy24;
	default:	goto yy13;
	}
yy16:
	++Cursor;
	{ CurrentToken = TOKEN_COLON;      goto end; }
yy18:
	++Cursor;
	{ CurrentToken = TOKEN_SEMICOLON;  goto end; }
yy20:
	++Cursor;
	{ CurrentToken = TOKEN_LESSER;     goto end; }
yy22:
	++Cursor;
	{ CurrentToken = TOKEN_GREATER;    goto end; }
yy24:
	++Cursor;
	yych = *Cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy24;
	default:	goto yy26;
	}
yy26:
	{ CurrentToken = TOKEN_IDENTIFIER; goto end; }
yy27:
	++Cursor;
	{ CurrentToken = TOKEN_LBRACE;     goto end; }
yy29:
	++Cursor;
	{ CurrentToken = TOKEN_RBRACE;     goto end; }
yy31:
	YYMARKER = ++Cursor;
	yych = *Cursor;
	switch (yych) {
	case '.':	goto yy36;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy31;
	default:	goto yy13;
	}
yy33:
	++Cursor;
	yych = *Cursor;
	switch (yych) {
	case '\n':	goto yy35;
	default:	goto yy33;
	}
yy35:
	{ PrevCursor = Cursor; goto start; }
yy36:
	yych = *++Cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy39;
	default:	goto yy37;
	}
yy37:
	Cursor = YYMARKER;
	goto yy13;
yy38:
	yych = *++Cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy42;
	default:	goto yy26;
	}
yy39:
	++Cursor;
	yych = *Cursor;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy39;
	default:	goto yy13;
	}
yy41:
	++Cursor;
	yych = *Cursor;
yy42:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy41;
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '_':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy24;
	default:	goto yy43;
	}
yy43:
	{ CurrentToken = TOKEN_HEXVAL;     goto end; }
}

	}

end:
	return CurrentToken;
}
